### ISSUE TITLE
Fix potential index out of bounds with 8ball command

### ISSUE THREAD

**Issue by develogix** [naterchrdsn/GReYBot#58]

**Comment by KnightVision90** [comment]
The way Math.random works is between 0 and 1 (1 being non inclusive). Therefore, the floor of the highest that can occur (say .99 for simplicity) multiplied by the length will never be equal to the length 

Assuming math random equal .99 and the length is 2 the floor will make it so the highest number achievable is 1 (rounding down from 1.98). Under your example and fix it would make it become .99 * (2-1) or .99 which will floor to 0, making the 2nd option never achievable.
